#cloud-config
hostname: web1.local
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses: [192.168.1.110/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
users:
  - name: root
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$PpJj5DiOzhxk7DJm$KaIpBS.mTozeEmTGrAri7A4EYf1D3O3pnGFxhwcMokjWLvRtJmfx8pCCvBAMqN6xx4jk8fs6GHWmMczcqVPVP0"
    ssh_pwauth: yes

package_update: true
package_upgrade: true
packages:
  - docker.io
runcmd:
  - docker run -d -p 80:80 nginx:latest
