---
- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  become: true
