---
galaxy_info:
  author: your_name
  description: Installs and configures Apache webserver.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - web
    - apache
    - http
